spring.application.name=debugger

spring.datasource.url=jdbc:mysql://localhost:3306/ai_debugger
spring.datasource.username=root
spring.datasource.password=Chitha@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

openrouter.api.key=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
